// Builds the Sotto logo from one source: the mark geometry below + the "sotto" wordmark
// outlined from DM Sans Medium. Writes src/components/brand/logoPaths.ts and public/brand/*.
// Run: node scripts/build-logo.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import opentype from 'opentype.js'
import { Resvg } from '@resvg/resvg-js'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const INK = '#14121C'
const WASH = '#F6F4FF'

// Mark, 32x32 grid: an open upper half-ring over a sealed lower half with a key slot cut out.
// "What sits below the line stays sealed."
const c = 16
const r = 13
const chordY = 18.6
const dx = Math.sqrt(r * r - (chordY - c) ** 2)
const MARK = [
  `M${c - r} ${c}A${r} ${r} 0 0 1 ${c + r} ${c}H${c + r - 3.2}A${r - 3.2} ${r - 3.2} 0 0 0 ${c - r + 3.2} ${c}Z`,
  `M${(c - dx).toFixed(3)} ${chordY}H${(c + dx).toFixed(3)}A${r} ${r} 0 0 1 ${(c - dx).toFixed(3)} ${chordY}Z`,
  // key slot (evenodd hole)
  'M14.5 22.1a1.5 1.5 0 0 1 3 0v3.2a1.5 1.5 0 0 1-3 0Z',
].join('')

// Wordmark: DM Sans Medium outlined to paths, tracking -0.02em, x-height centred on the mark.
const font = opentype.parse(readFileSync(join(root, 'scripts/fonts/DMSans-500.ttf')).buffer)
const SIZE = 26
const TRACK = -0.02 * SIZE
const xHeight = ((font.tables.os2.sxHeight || 500) / font.unitsPerEm) * SIZE
const baseline = 16 + xHeight / 2
const GAP = 7.5
let x = 32 + GAP
const parts = []
for (const ch of 'sotto') {
  const g = font.charToGlyph(ch)
  parts.push(g.getPath(x, baseline, SIZE).toPathData(2))
  x += (g.advanceWidth / font.unitsPerEm) * SIZE + TRACK
}
const WORD = parts.join('')
const FULL_W = Math.ceil(x - TRACK + 1)
const wordWidth = x - 32 - GAP

mkdirSync(join(root, 'src/components/brand'), { recursive: true })
writeFileSync(
  join(root, 'src/components/brand/logoPaths.ts'),
  `// Generated by scripts/build-logo.mjs. Do not edit by hand.\n` +
    `export const MARK_PATH = ${JSON.stringify(MARK)}\n` +
    `export const WORD_PATH = ${JSON.stringify(WORD)}\n` +
    `export const LOGO_WIDTH = ${FULL_W}\n`,
)

const logoSvg = (fill) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${FULL_W} 32" width="${FULL_W * 4}" height="128"><path fill-rule="evenodd" fill="${fill}" d="${MARK}"/><path fill="${fill}" d="${WORD}"/></svg>`
const markSvg = (fill) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path fill-rule="evenodd" fill="${fill}" d="${MARK}"/></svg>`

mkdirSync(join(root, 'public/brand'), { recursive: true })
writeFileSync(join(root, 'public/brand/logo.svg'), logoSvg(INK))
writeFileSync(join(root, 'public/brand/mark.svg'), markSvg(INK))
writeFileSync(
  join(root, 'public/favicon.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><style>path{fill:${INK}}@media (prefers-color-scheme:dark){path{fill:#DCD3FF}}</style><path fill-rule="evenodd" d="${MARK}"/></svg>`,
)

// 500x500 exports: logo centred with ~12% padding
const S = 500
const pad = S * 0.12
const scale = (S - 2 * pad) / FULL_W
const h = 32 * scale
const square = (bg) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="${S}" height="${S}" viewBox="0 0 ${S} ${S}">${bg ? `<rect width="${S}" height="${S}" fill="${bg}"/>` : ''}<g transform="translate(${pad} ${(S - h) / 2}) scale(${scale})"><path fill-rule="evenodd" fill="${INK}" d="${MARK}"/><path fill="${INK}" d="${WORD}"/></g></svg>`
for (const [name, bg] of [['logo-500.png', WASH], ['logo-500-transparent.png', null]]) {
  const png = new Resvg(square(bg), { fitTo: { mode: 'original' } }).render().asPng()
  writeFileSync(join(root, 'public/brand', name), png)
}
console.log('logo built', { FULL_W, wordWidth: wordWidth.toFixed(1) })
